name: Game Request
description: Game Request
labels: [game request]
body:
  - type: dropdown
    id: type
    attributes:
      label: Game Type
      multiple: false
      options:
        - Website ( eg 1v1 lol )
        - Offline HTML game ( eg Chroma Incident )
  - type: input
    id: gameurl
    attributes:
      label: Game URL
      placeholder: Link to the game url
    validations:
      required: false
  - type: textarea
    id: comment
    attributes:
      label: Comment
      placeholder: Leave a comment
    validations:
      required: true
